const settingsPermissions = {
  'PLM.SETTINGS.ORGANIZATION.VIEW': 'PLM.SETTINGS.ORGANIZATION.VIEW',
  'PLM.SETTINGS.ORGANIZATION.UPDATE': 'PLM.SETTINGS.ORGANIZATION.UPDATE',
  'PLM.SETTINGS.GENERAL.VIEW': 'PLM.SETTINGS.GENERAL.VIEW',
  'PLM.SETTINGS.GENERAL.UPDATE': 'PLM.SETTINGS.GENERAL.UPDATE',
  'PLM.SETTINGS.LOCALIZATION.VIEW': 'PLM.SETTINGS.LOCALIZATION.VIEW',
  'PLM.SETTINGS.LOCALIZATION.UPDATE': 'PLM.SETTINGS.LOCALIZATION.UPDATE',
  'PLM.SETTINGS.BRANDING.VIEW': 'PLM.SETTINGS.BRANDING.VIEW',
  'PLM.SETTINGS.BRANDING.UPDATE': 'PLM.SETTINGS.BRANDING.UPDATE',
} as const;

export default settingsPermissions;
