import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import prettierConfig from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import prettierPlugin from 'eslint-plugin-prettier';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
  ]),

  // Prettier
  prettierConfig,
  {
    plugins: {
      prettier: prettierPlugin,
    },
    rules: {
      'prettier/prettier': 'error',
    },
  },

  // Import
  {
    plugins: {
      import: importPlugin,
    },

    settings: {
      'import/resolver': {
        typescript: true,
      },
    },

    rules: {
      'import/order': [
        'error',
        {
          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
          'newlines-between': 'never',
          groups: ['builtin', 'external', 'parent', 'sibling', 'index'],
          pathGroups: [
            {
              pattern: 'react',
              group: 'external',
              position: 'before',
            },
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
        },
      ],
    },
  },

  // Sort import of Eslint
  {
    rules: {
      'sort-imports': ['error', { ignoreDeclarationSort: true }],
    },
  },

  // Import instead
  {
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'next/navigation',
              importNames: ['useRouter'],
              message: "Use useAppRouter from '@/core/router/next' instead.",
            },
            {
              name: 'next/link',
              message: "Use AppLink from '@/core/router/next' instead.",
            },
            {
              name: '@tanstack/react-query',
              importNames: ['useMutation', 'useQuery'],
              message:
                'Use a custom hook generated by createUseQuery___ from @/core/query/factories instead.',
            },
            {
              name: 'sonner',
              importNames: ['toast'],
              message: "Use notify from '@/core/notification' instead.",
            },
          ],
        },
      ],

      'no-restricted-globals': [
        'error',
        {
          name: 'fetch',
          message: "Use http-request from '@/core/network' instead.",
        },
      ],
    },
  },
]);

export default eslintConfig;
