const registryPermissions = {
  'PLM.REGISTRY.APP.CREATE': 'PLM.REGISTRY.APP.CREATE',
  'PLM.REGISTRY.APP.VIEW': 'PLM.REGISTRY.APP.VIEW',
  'PLM.REGISTRY.APP.UPDATE': 'PLM.REGISTRY.APP.UPDATE',
  'PLM.REGISTRY.APP.DELETE': 'PLM.REGISTRY.APP.DELETE',
} as const;

export default registryPermissions;
