const registryPermissions = {
  'PLM.REGISTRY.APP.CREATE': 'PLM.REGISTRY.APP.CREATE',
  'PLM.REGISTRY.APP.VIEW': 'PLM.REGISTRY.APP.VIEW',
  'PLM.REGISTRY.APP.UPDATE': 'PLM.REGISTRY.APP.UPDATE',
  'PLM.REGISTRY.APP.DELETE': 'PLM.REGISTRY.APP.DELETE',

  'PLM.REGISTRY.SERVICE.CREATE': 'PLM.REGISTRY.SERVICE.CREATE',
  'PLM.REGISTRY.SERVICE.VIEW': 'PLM.REGISTRY.SERVICE.VIEW',
  'PLM.REGISTRY.SERVICE.UPDATE': 'PLM.REGISTRY.SERVICE.UPDATE',
  'PLM.REGISTRY.SERVICE.DELETE': 'PLM.REGISTRY.SERVICE.DELETE',

  'PLM.REGISTRY.DOMAIN.CREATE': 'PLM.REGISTRY.DOMAIN.CREATE',
  'PLM.REGISTRY.DOMAIN.VIEW': 'PLM.REGISTRY.DOMAIN.VIEW',
  'PLM.REGISTRY.DOMAIN.UPDATE': 'PLM.REGISTRY.DOMAIN.UPDATE',
  'PLM.REGISTRY.DOMAIN.DELETE': 'PLM.REGISTRY.DOMAIN.DELETE',

  'PLM.REGISTRY.RESOURCE.CREATE': 'PLM.REGISTRY.RESOURCE.CREATE',
  'PLM.REGISTRY.RESOURCE.VIEW': 'PLM.REGISTRY.RESOURCE.VIEW',
  'PLM.REGISTRY.RESOURCE.UPDATE': 'PLM.REGISTRY.RESOURCE.UPDATE',
  'PLM.REGISTRY.RESOURCE.DELETE': 'PLM.REGISTRY.RESOURCE.DELETE',

  'PLM.REGISTRY.APP_SERVICE_MAPPING.ASSIGN':
    'PLM.REGISTRY.APP_SERVICE_MAPPING.ASSIGN',
  'PLM.REGISTRY.APP_SERVICE_MAPPING.UNASSIGN':
    'PLM.REGISTRY.APP_SERVICE_MAPPING.UNASSIGN',
  'PLM.REGISTRY.APP_SERVICE_MAPPING.VIEW':
    'PLM.REGISTRY.APP_SERVICE_MAPPING.VIEW',
} as const;

export default registryPermissions;
