const employeePermissions = {
  'HRM_EM.EMPLOYEE.EMPLOYEE.CREATE': 'HRM_EM.EMPLOYEE.EMPLOYEE.CREATE',
  'HRM_EM.EMPLOYEE.EMPLOYEE.VIEW': 'HRM_EM.EMPLOYEE.EMPLOYEE.VIEW',
  'HRM_EM.EMPLOYEE.EMPLOYEE.UPDATE': 'HRM_EM.EMPLOYEE.EMPLOYEE.UPDATE',
  'HRM_EM.EMPLOYEE.EMPLOYEE.DELETE': 'HRM_EM.EMPLOYEE.EMPLOYEE.DELETE',
} as const;

export default employeePermissions;
